---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

          ## Generating the testname for deployment
        - include_tasks: /ansible-utils/create_testname.yml

          ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'
        
        - name: username
          shell: cat /etc/secret-volume/username
          register: username
          
        - name: password
          shell: cat /etc/secret-volume/password
          register: password

        - name: Setting fail flag
          set_fact:
            flag: "Pass"

        - name: Change role of user mentioned by providing the emailId
          shell: python3 /api_testing/user-role/change-role.py  --url {{ director_url }} --username {{ username.stdout }} --password {{ password.stdout }} --group_id {{ group_id }} --member_emailId {{ self_emailId }} --role {{ item }}
          with_items:
            - "ProjectMember"
        
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      rescue:
        - name: Change role of user mentioned by providing the emailId
          shell: python3 /api_testing/user-role/change-role.py  --url {{ director_url }} --username {{ username.stdout }} --password {{ password.stdout }} --group_id {{ group_id }} --member_emailId {{ member_emailId }} --role {{ item }}
          with_items:
            - "ProjectOwner"

        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
