---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

          ## Generating the testname for deployment
        - include_tasks: /ansible-utils/create_testname.yml

          ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'

        - name : Fetch app 
          shell: kubectl get pods -n {{ namespace }} | grep configs-db | awk '{print $1}'
          register: app_pod
          failed_when: app_pod.stdout == ""

        - name : Check configs-db is present
          shell: kubectl exec -it {{ app_pod.stdout }} -n {{ namespace }} -- bash -c "psql -U postgres -h localhost <<< '\l'" | grep configs
          register: databases
          failed_when: "'configs' not in databases.stdout_lines[0]"
          
        - set_fact:
            flag: "Pass"

      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
