---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

          ## Generating the testname for deployment
        - include_tasks: /ansible-utils/create_testname.yml

          ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'

        - set_fact:
            director_url : "http://{{ director_ip }}:30380"

        - name: Get username
          shell: cat /etc/secret-volume/username
          register: username
            
        - name: Get password
          shell: cat /etc/secret-volume/password
          register: password

        - name: Get the number of CSP
          shell: kubectl get csp --no-headers | wc -l
          args:
            executable: /bin/bash
          register: csp_count

        - name: Checking whether all the pool pods are in running state before upgrading
          shell: kubectl get po -l app=cstor-pool -n openebs -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}' | wc -w
          register: pool_pods
          until: "pool_pods.stdout == csp_count.stdout"
          retries: 10
          delay: 5

        - name: Upgrade OpenEBS control plane
          shell: kubectl apply -f https://openebs.github.io/charts/openebs-operator-1.5.0.yaml
        
        - name: Fetch OpenEBS control plane pods state
          shell: kubectl get pods -n openebs  | grep {{ item }} | awk '{print $3}' | awk -F':' '{print $1}' | tail -n 1
          register: app_status
          until: app_status.stdout == 'Running'
          with_items:
            - "{{ openebs_components }}"
          retries: 20
          delay: 5
        
        - name: Fetch OpenEBS control plane pods ready status
          shell: kubectl get pods -n openebs | grep {{ item }} | awk '{print $2}' | awk -F'/' '{print $1}' && kubectl get pods -n openebs | grep {{ item }} | awk '{print $2}' | awk -F'/' '{print $2}'
          register: ready_status
          with_items:
            - "{{ openebs_components }}"
          until: "{{ ready_status.stdout_lines | unique | length == 1 }}"
          retries: 20
          delay: 5

        - set_fact:
            flag: "Pass"

      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
