---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: admin-cluster-connect
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: admin-cluster-connect-litmus
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      volumes:
      - name: secret-volume
        secret:
          secretName: director-admin-pass
      containers:
      - name: ansibletest
        image: mayadataio/dop-validator:ci
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
        env:
          - name: DIRECTOR_IP
            valueFrom:
              configMapKeyRef:
                name: config
                key: url
          - name: ANSIBLE_STDOUT_CALLBACK
            value: default  
          - name: PROVIDER
            value: gcp
          - name: CLUSTER_NAME
            value: OpenEBSDirector
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./litmus/director/admin-cluster-connect/test.yaml -i /etc/ansible/hosts -v; exit 0"]
      imagePullSecrets:
      - name: oep-secret