---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

          ## Generating the testname for deployment
        - include_tasks: /ansible-utils/create_testname.yml

          ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'
        
        - name: Fetch nodes
          shell: kubectl top nodes | tail -n +2 | awk '{print $1}' 
          register: nodes

        - name: Deploy openebs operator yaml
          shell: kubectl apply -f https://openebs.github.io/charts/openebs-operator-1.3.0.yaml
 
        - name: Create disks
          shell: gcloud compute disks create "disk-{{ item }}" --size=30GB --zone=us-east1-b
          with_items:
          - [1,2,3]
 
        - name: Attach disks
          shell: gcloud compute instances attach-disk {{ item.0 }} --disk "disk-{{ item.1 }}" --zone=us-east1-b --device-name="disks-{{ item.1 }}"
          with_together: 
          - "{{ nodes.stdout_lines }}"
          - [1,2,3]
        
        - name: sleep for 100 seconds for block devices to be discovered
          wait_for:
            timeout: 100

        - name: Fetch block devies
          shell: kubectl get bd -n openebs | tail -n +2 | awk '{print $1}' | head -n 3
          register: bd
        
        - name: Replace block devices in spc.yml
          shell: sed -i '{{ item.0 }} s/.*/    - {{ item.1 }}/' spc.yml
          with_together:
          - [14,15,16]
          - "{{ bd.stdout_lines }}"
    
        - name: Apply spc.yml to create cstor pools
          shell: kubectl apply -f ./litmus/prerequisite/spc.yml
        
        - name: Deploy minio application
          shell: kubectl apply -f ./litmus/prerequisite/minio.yml
  
        - set_fact:
            flag: "Pass"

      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
