apiVersion: v1
kind: Secret
metadata:
  name: oep-secret
  namespace: litmus
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFHRnljMmhwZEdGemFHRnliV0V3TVRFNlltaGhaRzFoYVc1cVlXOUFNVEl6IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOC4wOS43IChsaW51eCkiCgl9Cn0K
type: kubernetes.io/dockerconfigjson
