kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jiva-vol
  namespace: app-mongo-ns
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
---
