---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-claim
  namespace: delete-spc
  labels:
    app: minio-storage-claim
spec:
  storageClassName: cstor-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15G
