---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

          ## Generating the testname for deployment
        - include_tasks: /ansible-utils/create_testname.yml

          ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'

        - set_fact:
            director_url : "http://{{ director_ip }}:30380"

        - name: username
          shell: cat /etc/secret-volume/username
          register: username
          
        - name: password
          shell: cat /etc/secret-volume/password
          register: password
        
        - name: Fetch cortex-agent query metrics
          uri: 
              url: "{{ url }}/maya-cortex-pull/api/prom/api/v1/query?query={{ query }}"
              user: {{ username.stdout }}
              password: {{ password.stdout }}
              method: GET
              body_format: json
              status_code: 200
          register:  result

        - name: Check if cortex-agent is sending query metrics 
          shell: echo "{{ result.json.data.result }}"
          failed_when: result.json.data.result | length == 0

        - set_fact:
            flag: "Pass"

      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
